spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: devuser
    password: devuser
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
    
server:
  port: 8080
